### ISSUE TITLE
[Bug] Auth doesn't work for demo

### ISSUE THREAD

**Issue by andrewchmr** [ghoshnirmalya/nextjs-strapi-boilerplate#131]
**Description**

It's not possible to sign in on https://nextjs-strapi-boilerplate.vercel.app

**Steps:**
- Go to https://nextjs-strapi-boilerplate.vercel.app
- Click "Sign in"
- Click "Sign in with google"
- Choose your account

**Actual result**
![image](https://user-images.githubusercontent.com/43907473/104719022-1fe1c780-572c-11eb-9318-07771842bc16.png)

**Expected result**
Successful sign in

**Comment by marquez138** [comment]
any luck?

**Comment by ghoshnirmalya** [comment]
@andrewchmr Thank you for reporting this issue. This issue has been fixed. **The redirect URL to add in the Google application configurations** was wrong in the deployed application.
