### ISSUE TITLE
Google Auth - Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by omattman** [ghoshnirmalya/nextjs-strapi-boilerplate#31]
When authorizing with Google the following error occurs on client:

```
Error 400: redirect_uri_mismatch
The redirect URI in the request, http://localhost:3000/api/auth/callback/google, does not match the 
ones authorized for the OAuth client. To update the authorized redirect URIs, visit:
https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}
```

I have properly added the `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET` to my `.env` file. This is the following setup on my Google API credentials:

`Authorized JavaScript origins: http://localhost`
`Authorized redirect URIs: http://localhost:3000` **Remark**: I have also tried http://localhost:1337, but nothing works.

**Comment by ghoshnirmalya** [comment]
@omattman When you configured your Google API credentials, you need to add `http://localhost:1337/connect/google/callback` to **Authorized redirect URIs**.

**Comment by omattman** [comment]
@ghoshnirmalya ty for suggestion but did not work.

**Comment by ghoshnirmalya** [comment]
@omattman Please try the following:
1. Create a new **OAuth client ID**.
2. Choose **Web application** as the **Application Type**.
3. Add the following **Authorized redirect URIs**:
a. http://localhost:3000/api/auth/callback/google
b. http://localhost:1337/connect/google/callback
<img width="491" alt="Screenshot 2020-09-18 at 1 37 55 PM" src="https://user-images.githubusercontent.com/6391763/93573222-7d4f4d00-f9b4-11ea-80dd-ba913d4f2301.png">

4. Configure the **Google provider** in the Strapi admin panel.
<img width="1680" alt="Screenshot 2020-09-18 at 1 41 59 PM" src="https://user-images.githubusercontent.com/6391763/93573507-d7e8a900-f9b4-11ea-9a31-2846d088e5da.png">

5. Enable the **Google provider** in the Strapi admin panel.

If you try logging in now, it should work.

**Comment by omattman** [comment]
@ghoshnirmalya thanks! This did the trick for me as far as creating an account and logging in. Now another issue regarding "Error: forbidden" occurs when accessing protected pages. I'll close this issue and relate the previously mentioned issue in a new thread.
