### ISSUE TITLE
"Error: Forbidden" when accessing protected pages with Google provider

### ISSUE THREAD

**Issue by omattman** [ghoshnirmalya/nextjs-strapi-boilerplate#34]
After successfully having enabled Google Auth provider in #31 an another error occurred regarding protected pages when I have successfully created and logged in with the account.

When accessing `/my-account` I am met with the following error:

![image](https://user-images.githubusercontent.com/18309191/93629461-a689d080-f9e8-11ea-833d-3b31e3107a38.png)

Same applies for `/feeds`. However enabling `find` action on the `feeds` type for authorized users allow me to access the page properly. How do we handle cases where a page is not necessarily added through the backend as `my-account` but is instead added in the project via the `page` folder?

**Comment by ghoshnirmalya** [comment]
@omattman Did you following [this step](https://github.com/ghoshnirmalya/nextjs-strapi-boilerplate#8-configure-strapi)?

**Comment by omattman** [comment]
@ghoshnirmalya yes I've done it for the `feeds` type, but when accessing `my-account` it returns the error.

**Comment by omattman** [comment]
@ghoshnirmalya did a clean install and it works perfect now. Might have had an issue when first creating the project.
